export type DietaryTag = 'vegetarian' | 'vegan' | 'gluten-free' | 'halal' | 'dairy-free';

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image: string;
  available: boolean;
  dietaryTags?: DietaryTag[];
  featured?: boolean;
  nutritionInfo?: {
    calories?: number;
    protein?: number;
    carbs?: number;
    fat?: number;
  };
}

export interface MenuCategory {
  id: string;
  name: string;
  description?: string;
}

export const menuCategories: MenuCategory[] = [
  { id: 'all', name: 'All Items' },
  { id: 'breakfast', name: 'Breakfast' },
  { id: 'burgers', name: 'Burgers & Combos' },
  { id: 'pizzas', name: 'Pizzas' },
  { id: 'mains', name: 'Main Meals' },
  { id: 'platters', name: 'Platters' },
  { id: 'salads', name: 'Salads & Sandwiches' },
  { id: 'sides', name: 'Sides & Snacks' },
  { id: 'hot-coffee', name: 'Hot Coffee' },
  { id: 'tea', name: 'Tea & Hot Drinks' },
  { id: 'iced', name: 'Iced Coffee & Tea' },
  { id: 'juices', name: 'Juices & Smoothies' },
  { id: 'desserts', name: 'Shakes & Desserts' },
  { id: 'mocktails', name: 'Mocktails' },
  { id: 'cocktails', name: 'Cocktails' },
  { id: 'beer', name: 'Beer & Energy Drinks' },
  { id: 'spirits', name: 'Spirits' },
  { id: 'wines', name: 'Wines' },
  { id: 'water', name: 'Water & Soda' },
  { id: 'retail', name: 'Retail' },
];

export const dummyMenuItems: MenuItem[] = [
  // BREAKFAST
  {
    id: 'breakfast-1',
    name: 'Full English Breakfast',
    description: 'Complete breakfast with eggs, bacon, sausage, baked beans, mushrooms, and toast',
    price: 1200,
    category: 'breakfast',
    image: '/images/menu/breakfast2.jpeg',
    available: true,
    featured: true,
  },
  {
    id: 'breakfast-2',
    name: 'Urban Oats Meat Bliss',
    description: 'Hearty oats with meat toppings',
    price: 500,
    category: 'breakfast',
    image: '/images/menu/oats.jpeg',
    available: true,
  },
  {
    id: 'breakfast-3',
    name: 'Urban Healthy Option',
    description: 'Nutritious breakfast options',
    price: 500,
    category: 'breakfast',
    image: '/images/menu/breakfast.jpg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'breakfast-4',
    name: 'Pancakes (3 pcs)',
    description: 'Fluffy pancakes served with syrup',
    price: 350,
    category: 'breakfast',
    image: '/images/menu/breakfast.jpg',
    available: true,
    dietaryTags: ['vegetarian'],
  },

  // BURGERS & COMBOS
  {
    id: 'burger-1',
    name: 'Beef Burger Bacon (No Cheese)',
    description: 'Beef patty with bacon, no cheese',
    price: 650,
    category: 'burgers',
    image: '/images/menu/burger.jpeg',
    available: true,
  },
  {
    id: 'burger-2',
    name: 'Beef Cheese Burger',
    description: 'Premium beef patty with melted cheese',
    price: 1050,
    category: 'burgers',
    image: '/images/menu/burger1.jpeg',
    available: true,
    featured: true,
  },
  {
    id: 'burger-3',
    name: 'Bacon Cheese Burger',
    description: 'Crispy bacon with melted cheese',
    price: 1000,
    category: 'burgers',
    image: '/images/menu/burger2.jpeg',
    available: true,
  },
  {
    id: 'burger-4',
    name: 'Chicken Cheese Burger',
    description: 'Tender chicken patty with cheese',
    price: 1150,
    category: 'burgers',
    image: '/images/menu/burger.jpeg',
    available: true,
  },
  {
    id: 'burger-5',
    name: 'Urban Decker Burger',
    description: 'Premium double-stacked burger',
    price: 1500,
    category: 'burgers',
    image: '/images/menu/burger1.jpeg',
    available: true,
    featured: true,
  },
  {
    id: 'burger-6',
    name: 'Urban Vege Burger',
    description: 'Delicious vegetarian burger',
    price: 750,
    category: 'burgers',
    image: '/images/menu/burger2.jpeg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'burger-7',
    name: 'FreakyShake Burger',
    description: 'Unique burger with special sauce',
    price: 1900,
    category: 'burgers',
    image: '/images/menu/burger.jpeg',
    available: true,
  },
  {
    id: 'burger-8',
    name: 'Sodalicios Burger',
    description: 'Special recipe burger',
    price: 1034,
    category: 'burgers',
    image: '/images/menu/burger1.jpeg',
    available: true,
  },
  {
    id: 'burger-9',
    name: 'Burger Shake Combo',
    description: 'Burger with shake included',
    price: 1250,
    category: 'burgers',
    image: '/images/menu/burger2.jpeg',
    available: true,
  },
  {
    id: 'burger-10',
    name: 'Burger Smoothies Combo',
    description: 'Burger with smoothie included',
    price: 1207,
    category: 'burgers',
    image: '/images/menu/burger.jpeg',
    available: true,
  },
  {
    id: 'burger-11',
    name: 'Kids Beef Burger',
    description: 'Small beef burger for kids',
    price: 500,
    category: 'burgers',
    image: '/images/menu/burger1.jpeg',
    available: true,
  },

  // PIZZAS
  {
    id: 'pizza-1',
    name: 'Margarita Pizza Small',
    description: 'Classic pizza with mozzarella, tomato, and basil',
    price: 700,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'pizza-2',
    name: 'Margarita Pizza Medium',
    description: 'Classic pizza with mozzarella, tomato, and basil',
    price: 1000,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'pizza-3',
    name: 'Margarita Pizza Large',
    description: 'Classic pizza with mozzarella, tomato, and basil',
    price: 1200,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'pizza-4',
    name: 'Pepperoni Pizza Small',
    description: 'Pizza with fresh pepperoni',
    price: 800,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-5',
    name: 'Pepperoni Pizza Medium',
    description: 'Pizza with fresh pepperoni',
    price: 1200,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-6',
    name: 'Pepperoni Pizza Large',
    description: 'Pizza with fresh pepperoni',
    price: 1500,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-7',
    name: 'Barbecue Pollo Pizza Small',
    description: 'BBQ chicken pizza',
    price: 900,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-8',
    name: 'Barbecue Pollo Pizza Medium',
    description: 'BBQ chicken pizza',
    price: 1300,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-9',
    name: 'Barbecue Pollo Pizza Large',
    description: 'BBQ chicken pizza',
    price: 1600,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-10',
    name: 'Hawaiian Pizza Small',
    description: 'Pizza with pineapple and ham',
    price: 800,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-11',
    name: 'Hawaiian Pizza Medium',
    description: 'Pizza with pineapple and ham',
    price: 1300,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-12',
    name: 'Hawaiian Pizza Large',
    description: 'Pizza with pineapple and ham',
    price: 1600,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-13',
    name: 'Meat Lovers Urban Pizza Small',
    description: 'Loaded with different meats',
    price: 1200,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-14',
    name: 'Meat Lovers Urban Pizza Medium',
    description: 'Loaded with different meats',
    price: 1500,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-15',
    name: 'Meat Lovers Urban Pizza Large',
    description: 'Loaded with different meats',
    price: 2000,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-16',
    name: 'Urban Nile Pizza Small',
    description: 'Special Urban Nile recipe',
    price: 1100,
    category: 'pizzas',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'pizza-17',
    name: 'Urban Nile Pizza Medium',
    description: 'Special Urban Nile recipe',
    price: 1400,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },
  {
    id: 'pizza-18',
    name: 'Urban Nile Pizza Large',
    description: 'Special Urban Nile recipe',
    price: 1800,
    category: 'pizzas',
    image: '/images/menu/pizza.jpeg',
    available: true,
  },

  // MAIN MEALS - BEEF
  {
    id: 'main-beef-1',
    name: 'Steak Wet Fry',
    description: 'Beef steak with wet fries',
    price: 800,
    category: 'mains',
    image: '/images/menu/main-course-1.jpg',
    available: true,
  },
  {
    id: 'main-beef-2',
    name: 'Steak Dry Fry',
    description: 'Beef steak with dry fries',
    price: 800,
    category: 'mains',
    image: '/images/menu/main-course-1.jpg',
    available: true,
  },
  {
    id: 'main-beef-3',
    name: 'Beef Pilau',
    description: 'Beef with fragrant rice',
    price: 800,
    category: 'mains',
    image: '/images/menu/pilau.jpeg',
    available: true,
  },
  {
    id: 'main-beef-4',
    name: 'Beef Biryani',
    description: 'Beef with spiced rice',
    price: 800,
    category: 'mains',
    image: '/images/menu/pilau.jpeg',
    available: true,
  },
  {
    id: 'main-beef-5',
    name: 'Beef Grilled',
    description: 'Grilled beef steak',
    price: 900,
    category: 'mains',
    image: '/images/menu/main-course-1.jpg',
    available: true,
  },
  {
    id: 'main-beef-6',
    name: 'Beef Grilled with Plantain',
    description: 'Grilled beef with plantain sides',
    price: 1525,
    category: 'mains',
    image: '/images/menu/plantain.jpeg',
    available: true,
  },
  {
    id: 'main-beef-7',
    name: 'Beef Chapati',
    description: 'Beef with Indian flatbread',
    price: 850,
    category: 'mains',
    image: '/images/menu/main-course-1.jpg',
    available: true,
  },

  // MAIN MEALS - CHICKEN
  {
    id: 'main-chicken-1',
    name: 'Chicken Kienyeji',
    description: 'Traditional cooked chicken',
    price: 850,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-2',
    name: 'Chicken Kienyeji Grilled',
    description: 'Grilled traditional chicken',
    price: 900,
    category: 'mains',
    image: '/images/menu/z.mp4',
    available: true,
  },
  {
    id: 'main-chicken-3',
    name: 'Chicken Drumsticks (3 pcs)',
    description: 'Three pieces of chicken drumsticks',
    price: 750,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-4',
    name: 'Chicken Wings (3 pcs)',
    description: 'Three pieces of chicken wings',
    price: 750,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-5',
    name: 'Chicken Pilau',
    description: 'Chicken with fragrant rice',
    price: 850,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-6',
    name: 'Chicken Biryani',
    description: 'Chicken with spiced rice',
    price: 950,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-7',
    name: 'Chicken Curry',
    description: 'Chicken in aromatic curry sauce',
    price: 820,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-8',
    name: 'Chicken Vindaloo',
    description: 'Spicy chicken curry',
    price: 950,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-9',
    name: 'Coated Chicken Breast',
    description: 'Crispy coated chicken breast',
    price: 950,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-10',
    name: 'Grilled Chicken with Plantain',
    description: 'Grilled chicken with plantain sides',
    price: 1525,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-11',
    name: 'Chicken Schnitzel',
    description: 'Breaded and fried chicken',
    price: 550,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },
  {
    id: 'main-chicken-12',
    name: 'Chicken Little',
    description: 'Small portion of chicken',
    price: 575,
    category: 'mains',
    image: '/images/menu/main-course-2.jpg',
    available: true,
  },

  // MAIN MEALS - FISH
  {
    id: 'main-fish-1',
    name: 'Whole Tilapia Fish',
    description: 'Whole fresh tilapia fish',
    price: 850,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'main-fish-2',
    name: 'Whole Tilapia Fish Grilled',
    description: 'Grilled whole tilapia fish',
    price: 900,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'main-fish-3',
    name: 'Swahili Coconut Fish',
    description: 'Fish in creamy coconut sauce',
    price: 950,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'main-fish-4',
    name: 'Grilled Fish Fillet',
    description: 'Grilled fish fillet',
    price: 900,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'main-fish-5',
    name: 'Grilled Fish with Plantain',
    description: 'Grilled fish with plantain sides',
    price: 1525,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'main-fish-6',
    name: 'Fish Fillet',
    description: 'Premium fish fillet',
    price: 1050,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'main-fish-7',
    name: 'Fish Fingers',
    description: 'Crispy fish fingers',
    price: 900,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },

  // MAIN MEALS - VEGETARIAN
  {
    id: 'main-veg-1',
    name: 'Veggie Biryani',
    description: 'Vegetables with spiced rice',
    price: 650,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'main-veg-2',
    name: 'Vegetable Rice',
    description: 'Rice with mixed vegetables',
    price: 300,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'main-veg-3',
    name: 'Spinach',
    description: 'Fresh cooked spinach',
    price: 100,
    category: 'mains',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },

  // PLATTERS
  {
    id: 'platter-1',
    name: 'Weekend Platter',
    description: 'Assorted meats and sides',
    price: 3850,
    category: 'platters',
    image: '/images/menu/platter.jpeg',
    available: true,
    featured: true,
  },
  {
    id: 'platter-2',
    name: 'Platter â€“ 2',
    description: 'Platter for two people',
    price: 2500,
    category: 'platters',
    image: '/images/menu/platter1.jpeg',
    available: true,
  },
  {
    id: 'platter-3',
    name: 'Urban Platter â€“ 4',
    description: 'Platter for four people',
    price: 4500,
    category: 'platters',
    image: '/images/menu/platter2.jpeg',
    available: true,
  },
  {
    id: 'platter-4',
    name: 'House of Plenty Platter',
    description: 'Large family platter',
    price: 6900,
    category: 'platters',
    image: '/images/menu/platter3.jpeg',
    available: true,
  },
  {
    id: 'platter-5',
    name: 'Fingers Nuggets Combo',
    description: 'Assorted fingers and nuggets',
    price: 2300,
    category: 'platters',
    image: '/images/menu/platter4.jpeg',
    available: true,
  },

  // SALADS & SANDWICHES
  {
    id: 'salad-1',
    name: 'Garden Salad',
    description: 'Fresh mixed greens',
    price: 550,
    category: 'salads',
    image: '/images/menu/salad .jpg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'salad-2',
    name: 'Chicken Caesar Salad',
    description: 'Crisp salad with grilled chicken',
    price: 950,
    category: 'salads',
    image: '/images/menu/salad1.jpeg',
    available: true,
  },
  {
    id: 'salad-3',
    name: 'Thai Mango Salad',
    description: 'Thai-style mango salad',
    price: 500,
    category: 'salads',
    image: '/images/menu/salad2.jpeg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'sandwich-1',
    name: 'Chicken Sandwich',
    description: 'Grilled chicken sandwich',
    price: 900,
    category: 'salads',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'sandwich-2',
    name: 'Beef Sandwich',
    description: 'Tender beef sandwich',
    price: 800,
    category: 'salads',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'sandwich-3',
    name: 'Egg Sandwich',
    description: 'Fresh egg sandwich',
    price: 900,
    category: 'salads',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'sandwich-4',
    name: 'Vegetable Sandwich',
    description: 'Fresh vegetable sandwich',
    price: 700,
    category: 'salads',
    image: '/images/menu/salad.jpeg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'sandwich-5',
    name: 'Fruit Sandwich',
    description: 'Fresh fruit sandwich',
    price: 450,
    category: 'salads',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'salad-extra-1',
    name: 'Extra Cheese',
    description: 'Additional cheese topping',
    price: 200,
    category: 'salads',
    image: '/images/menu/salad2.jpeg',
    available: true,
    dietaryTags: ['vegetarian'],
  },

  // SIDES & SNACKS
  {
    id: 'sides-1',
    name: 'Fries Plain',
    description: 'Classic plain fries',
    price: 350,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'sides-2',
    name: 'Chips Masala',
    description: 'Fries with masala seasoning',
    price: 400,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'sides-3',
    name: 'Potato Wedges',
    description: 'Golden potato wedges',
    price: 400,
    category: 'sides',
    image: '/images/menu/potato_wedges.jpeg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'sides-4',
    name: 'Garlic Cheese Wedges',
    description: 'Wedges with garlic and cheese',
    price: 550,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'sides-5',
    name: 'Hot Dog',
    description: 'Classic hot dog',
    price: 400,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'sides-6',
    name: 'Kebab',
    description: 'Grilled meat kebab',
    price: 500,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'sides-7',
    name: 'Samosa Mega (2 pcs)',
    description: 'Two pieces of samosa',
    price: 250,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'sides-8',
    name: 'Sausages (2 pcs)',
    description: 'Two pieces of sausages',
    price: 220,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'sides-9',
    name: 'Plantain',
    description: 'Fried plantain slices',
    price: 800,
    category: 'sides',
    image: '/images/menu/plantain.jpeg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'sides-10',
    name: 'Ugali White',
    description: 'White cornmeal',
    price: 50,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'sides-11',
    name: 'Ugali Brown',
    description: 'Brown cornmeal',
    price: 100,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'sides-12',
    name: 'Extra Honey',
    description: 'Additional honey',
    price: 60,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'sides-13',
    name: 'Masala Pot',
    description: 'Spiced masala dish',
    price: 600,
    category: 'sides',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },

  // HOT COFFEE
  {
    id: 'coffee-1',
    name: 'Americano Black (Single)',
    description: 'Single shot of espresso with hot water',
    price: 250,
    category: 'hot-coffee',
    image: '/images/menu/espresso.jpg',
    available: true,
  },
  {
    id: 'coffee-2',
    name: 'Americano Black (Double)',
    description: 'Double shot of espresso with hot water',
    price: 400,
    category: 'hot-coffee',
    image: '/images/menu/espresso.jpg',
    available: true,
  },
  {
    id: 'coffee-3',
    name: 'Espresso Black (Single)',
    description: 'Single shot of strong espresso',
    price: 250,
    category: 'hot-coffee',
    image: '/images/menu/espresso.jpg',
    available: true,
  },
  {
    id: 'coffee-4',
    name: 'Espresso Black (Double)',
    description: 'Double shot of strong espresso',
    price: 400,
    category: 'hot-coffee',
    image: '/images/menu/espresso.jpg',
    available: true,
  },
  {
    id: 'coffee-5',
    name: 'Latte White (Single)',
    description: 'Espresso with steamed milk',
    price: 350,
    category: 'hot-coffee',
    image: '/images/menu/cappuccino.jpg',
    available: true,
  },
  {
    id: 'coffee-6',
    name: 'Latte White (Double)',
    description: 'Double espresso with steamed milk',
    price: 400,
    category: 'hot-coffee',
    image: '/images/menu/cappuccino.jpg',
    available: true,
  },
  {
    id: 'coffee-7',
    name: 'Cappuccino White (Single)',
    description: 'Espresso with velvety microfoam',
    price: 350,
    category: 'hot-coffee',
    image: '/images/menu/cappuccino.jpg',
    available: true,
  },
  {
    id: 'coffee-8',
    name: 'Cappuccino White (Double)',
    description: 'Double espresso with velvety microfoam',
    price: 450,
    category: 'hot-coffee',
    image: '/images/menu/cappuccino.jpg',
    available: true,
  },
  {
    id: 'coffee-9',
    name: 'Macchiato (Single)',
    description: 'Espresso marked with foam',
    price: 350,
    category: 'hot-coffee',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'coffee-10',
    name: 'Macchiato (Double)',
    description: 'Double espresso marked with foam',
    price: 400,
    category: 'hot-coffee',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'coffee-11',
    name: 'White Mocha (Single)',
    description: 'Espresso with chocolate and steamed milk',
    price: 350,
    category: 'hot-coffee',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'coffee-12',
    name: 'White Mocha (Double)',
    description: 'Double espresso with chocolate and steamed milk',
    price: 400,
    category: 'hot-coffee',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'coffee-13',
    name: 'Flavoured Coffee',
    description: 'Coffee with flavored syrup',
    price: 350,
    category: 'hot-coffee',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'coffee-14',
    name: 'Extra Flavoured Syrup',
    description: 'Additional flavored syrup',
    price: 200,
    category: 'hot-coffee',
    image: '/images/menu/hot-coffee.jpg',
    available: true,
  },
  {
    id: 'coffee-15',
    name: 'Irish Coffee',
    description: 'Coffee with Irish whiskey',
    price: 850,
    category: 'hot-coffee',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },

  // TEA & HOT DRINKS
  {
    id: 'tea-1',
    name: 'Black Tea',
    description: 'Classic black tea',
    price: 270,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'tea-2',
    name: 'Lemon Tea',
    description: 'Black tea with lemon',
    price: 270,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'tea-3',
    name: 'Masala Tea',
    description: 'Spiced tea with milk',
    price: 320,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'tea-4',
    name: 'Herbal Tea',
    description: 'Assorted herbal tea',
    price: 320,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'tea-5',
    name: 'Mixed Tea',
    description: 'Mixed variety of tea',
    price: 320,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'tea-6',
    name: 'Tea Pot',
    description: 'Pot of tea for sharing',
    price: 650,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'tea-7',
    name: 'Hot Milk / Glass of Milk',
    description: 'Warm milk glass',
    price: 150,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'tea-8',
    name: 'Hot Water Lemon',
    description: 'Hot water with lemon',
    price: 200,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'tea-9',
    name: 'Urban Dawa',
    description: 'Traditional ginger drink',
    price: 370,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'tea-10',
    name: 'Signature Dawa',
    description: 'Special ginger honey drink',
    price: 400,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'tea-11',
    name: 'Hot Lime/Ginger/Honey',
    description: 'Warm citrus ginger honey drink',
    price: 390,
    category: 'tea',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },

  // ICED COFFEE & TEA
  {
    id: 'iced-1',
    name: 'Iced Latte (Single)',
    description: 'Cold espresso with milk',
    price: 390,
    category: 'iced',
    image: '/images/menu/icedlatte.jpeg',
    available: true,
  },
  {
    id: 'iced-2',
    name: 'Iced Latte (Double)',
    description: 'Cold double espresso with milk',
    price: 400,
    category: 'iced',
    image: '/images/menu/icedlatte.jpeg',
    available: true,
  },
  {
    id: 'iced-3',
    name: 'Iced Americano Black',
    description: 'Cold americano',
    price: 390,
    category: 'iced',
    image: '/images/menu/icedlatte.jpeg',
    available: true,
  },
  {
    id: 'iced-4',
    name: 'Iced Cappuccino (Single)',
    description: 'Cold cappuccino',
    price: 390,
    category: 'iced',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'iced-5',
    name: 'Iced Cappuccino (Double)',
    description: 'Cold double cappuccino',
    price: 450,
    category: 'iced',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'iced-6',
    name: 'Iced Mocha',
    description: 'Cold mocha with chocolate',
    price: 390,
    category: 'iced',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'iced-7',
    name: 'Iced Lemon Coffee',
    description: 'Cold coffee with lemon',
    price: 390,
    category: 'iced',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'iced-8',
    name: 'Iced Tea',
    description: 'Cold tea',
    price: 390,
    category: 'iced',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'iced-9',
    name: 'Iced Lemon/Ginger',
    description: 'Cold lemon and ginger drink',
    price: 390,
    category: 'iced',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'iced-10',
    name: 'Iced Herbal Tea',
    description: 'Cold herbal tea',
    price: 390,
    category: 'iced',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'iced-11',
    name: 'Iced Passion Tea',
    description: 'Cold passion fruit tea',
    price: 390,
    category: 'iced',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },

  // JUICES & SMOOTHIES
  {
    id: 'juice-1',
    name: 'Pineapple Juice',
    description: 'Fresh pineapple juice',
    price: 400,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'juice-2',
    name: 'Orange Juice',
    description: 'Fresh orange juice',
    price: 400,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'juice-3',
    name: 'Mango Juice',
    description: 'Fresh mango juice',
    price: 400,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'juice-4',
    name: 'Passion Juice',
    description: 'Fresh passion fruit juice',
    price: 400,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'juice-5',
    name: 'Tamarind Juice',
    description: 'Fresh tamarind juice',
    price: 450,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'juice-6',
    name: 'Cocktail Juice',
    description: 'Mixed fruit cocktail juice',
    price: 550,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'smoothie-1',
    name: 'Mint Smoothie',
    description: 'Cooling mint smoothie',
    price: 350,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'smoothie-2',
    name: 'Mango Smoothie',
    description: 'Creamy mango smoothie',
    price: 350,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'smoothie-3',
    name: 'Banana Smoothie',
    description: 'Rich banana smoothie',
    price: 350,
    category: 'juices',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },

  // SHAKES & DESSERTS
  {
    id: 'dessert-1',
    name: 'FreakyShakes (All Flavours)',
    description: 'Unique flavored shakes',
    price: 750,
    category: 'desserts',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    featured: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-2',
    name: 'Cappuccino Shake',
    description: 'Coffee-flavored shake',
    price: 400,
    category: 'desserts',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-3',
    name: 'Urban Shake',
    description: 'House specialty shake',
    price: 400,
    category: 'desserts',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-4',
    name: 'Mocha Shake',
    description: 'Mocha coffee shake',
    price: 400,
    category: 'desserts',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-5',
    name: 'Mango Shake',
    description: 'Fresh mango shake',
    price: 400,
    category: 'desserts',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-6',
    name: 'Kids Shake',
    description: 'Small shake for kids',
    price: 250,
    category: 'desserts',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-7',
    name: 'Ice Cream Scoop',
    description: 'Single scoop of ice cream',
    price: 380,
    category: 'desserts',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-8',
    name: 'Banana Split',
    description: 'Classic banana split',
    price: 350,
    category: 'desserts',
    image: '/images/menu/chocolate-lava-cake.jpg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-9',
    name: 'Portion Split',
    description: 'Large banana split',
    price: 1000,
    category: 'desserts',
    image: '/images/menu/chocolate-lava-cake.jpg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-10',
    name: 'Piece of Cake',
    description: 'Slice of fresh cake',
    price: 1000,
    category: 'desserts',
    image: '/images/menu/chocolate-lava-cake.jpg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'dessert-11',
    name: 'ChocoChip Cookie',
    description: 'Chocolate chip cookie',
    price: 400,
    category: 'desserts',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },

  // MOCKTAILS
  {
    id: 'mocktail-1',
    name: 'Virgin Mojito',
    description: 'Refreshing mint mojito without alcohol',
    price: 400,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'mocktail-2',
    name: 'Classic Lemonade',
    description: 'Freshly made lemonade',
    price: 400,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'mocktail-3',
    name: 'Strawberry Lemonade',
    description: 'Strawberry flavored lemonade',
    price: 400,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'mocktail-4',
    name: 'Passion Lemonade',
    description: 'Passion fruit lemonade',
    price: 450,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'mocktail-5',
    name: 'Limeade Punch',
    description: 'Lime flavored punch',
    price: 400,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'mocktail-6',
    name: 'Cotton Candy',
    description: 'Sweet cotton candy drink',
    price: 400,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'mocktail-7',
    name: 'Sunset',
    description: 'Sunset colored mocktail',
    price: 400,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'mocktail-8',
    name: 'Masala Soda',
    description: 'Spiced soda drink',
    price: 650,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'mocktail-9',
    name: 'Mango Lassi',
    description: 'Traditional mango yogurt drink',
    price: 650,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'mocktail-10',
    name: 'Am Panna',
    description: 'Raw mango drink',
    price: 650,
    category: 'mocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },

  // COCKTAILS
  {
    id: 'cocktail-1',
    name: 'Long Island',
    description: 'Long Island Iced Tea',
    price: 950,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-2',
    name: 'Whiskey Sour',
    description: 'Classic whiskey sour',
    price: 950,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-3',
    name: 'Margarita',
    description: 'Classic margarita',
    price: 900,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-4',
    name: 'Mojito',
    description: 'Rum mojito with mint',
    price: 950,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-5',
    name: 'Moscow Mule',
    description: 'Vodka ginger beer cocktail',
    price: 1500,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-6',
    name: 'Sangria',
    description: 'Wine fruit punch',
    price: 900,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-7',
    name: 'JÃ¤ger Bomb',
    description: 'JÃ¤germeister energy drink bomb',
    price: 1200,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-8',
    name: 'PiÃ±a Colada',
    description: 'Coconut rum cocktail',
    price: 400,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-9',
    name: 'Mango Mule',
    description: 'Mango vodka ginger beer',
    price: 900,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-10',
    name: 'Monkey Business',
    description: 'Exotic rum cocktail',
    price: 1000,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-11',
    name: 'The Governor',
    description: 'Premium whiskey cocktail',
    price: 900,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-12',
    name: 'Bishop',
    description: 'Brandy wine cocktail',
    price: 1200,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'cocktail-13',
    name: 'Trust Me You Can Dance',
    description: 'Party favorite cocktail',
    price: 1800,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    featured: true,
  },
  {
    id: 'cocktail-14',
    name: 'Furaha Cocktails',
    description: 'Celebration cocktail',
    price: 10700,
    category: 'cocktails',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },

  // BEER & ENERGY DRINKS
  {
    id: 'beer-1',
    name: 'Heineken 330ml',
    description: 'Premium beer',
    price: 600,
    category: 'beer',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'beer-2',
    name: 'Heineken Zero 330ml',
    description: 'Non-alcoholic beer',
    price: 600,
    category: 'beer',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'beer-3',
    name: 'Desperados 330ml',
    description: 'Tequila flavored beer',
    price: 600,
    category: 'beer',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'beer-4',
    name: 'Savannah Dry 330ml',
    description: 'Local dry beer',
    price: 600,
    category: 'beer',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'beer-5',
    name: 'Red Bull 250ml',
    description: 'Energy drink',
    price: 550,
    category: 'beer',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },

  // SPIRITS
  {
    id: 'spirit-1',
    name: 'Jack Daniel\'s 750ml',
    description: 'Premium whiskey bottle',
    price: 6000,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-2',
    name: 'Johnnie Walker Black 750ml',
    description: 'Blended whiskey bottle',
    price: 6000,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-3',
    name: 'Johnnie Walker Black 1L',
    description: 'Blended whiskey 1 liter',
    price: 9500,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-4',
    name: 'Glenfiddich 12yrs 750ml',
    description: 'Single malt whiskey',
    price: 14000,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-5',
    name: 'Singleton 12yrs 750ml',
    description: 'Premium single malt',
    price: 14500,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-6',
    name: 'Singleton 15yrs 750ml',
    description: 'Premium aged single malt',
    price: 13000,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-7',
    name: 'Martell VS 750ml',
    description: 'Cognac bottle',
    price: 12000,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-8',
    name: 'Blue Curacao 750ml',
    description: 'Orange liqueur',
    price: 5000,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-9',
    name: 'Bacardi Shot',
    description: 'Single shot of Bacardi',
    price: 400,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-10',
    name: 'JW Black Label Shot',
    description: 'Single shot of Johnnie Walker Black',
    price: 450,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-11',
    name: 'JW Red Label Shot',
    description: 'Single shot of Johnnie Walker Red',
    price: 400,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-12',
    name: 'Gilbey\'s Shot',
    description: 'Single shot of Gilbey\'s Gin',
    price: 300,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-13',
    name: 'Glenfiddich Shot',
    description: 'Single shot of Glenfiddich',
    price: 550,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-14',
    name: 'Singleton Shot',
    description: 'Single shot of Singleton',
    price: 500,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-15',
    name: 'Smirnoff Vodka Shot',
    description: 'Single shot of Smirnoff',
    price: 300,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-16',
    name: 'Tequila Shot',
    description: 'Single shot of Tequila',
    price: 350,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-17',
    name: 'JÃ¤germeister Shot',
    description: 'Single shot of JÃ¤germeister',
    price: 400,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'spirit-18',
    name: 'Martell Shot',
    description: 'Single shot of Martell Cognac',
    price: 550,
    category: 'spirits',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },

  // WINES
  {
    id: 'wine-1',
    name: '4th Street Sweet Red',
    description: 'Sweet red wine',
    price: 800,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-2',
    name: '4th Street Sweet White',
    description: 'Sweet white wine',
    price: 800,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-3',
    name: '4th Street Dry Red 750ml',
    description: 'Dry red wine',
    price: 2500,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-4',
    name: '4th Street Dry White 750ml',
    description: 'Dry white wine',
    price: 2500,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-5',
    name: 'Cellar Cask Sweet Red',
    description: 'Sweet red wine',
    price: 800,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-6',
    name: 'Cellar Cask Sweet White',
    description: 'Sweet white wine',
    price: 800,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-7',
    name: 'Four Cousins Sweet Red',
    description: 'Sweet red wine',
    price: 3000,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-8',
    name: 'Four Cousins Sweet White',
    description: 'Sweet white wine',
    price: 800,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-9',
    name: 'Four Cousins Sweet Red 750ml',
    description: 'Sweet red wine 750ml',
    price: 800,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-10',
    name: 'Drostdhof Sweet White',
    description: 'Sweet white wine',
    price: 2850,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-11',
    name: 'Drostdhof Dry White 750ml',
    description: 'Dry white wine',
    price: 2850,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-12',
    name: 'Frontera Sweet Red',
    description: 'Sweet red wine',
    price: 800,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
  {
    id: 'wine-13',
    name: 'Glass of Wine',
    description: 'Single glass of wine',
    price: 800,
    category: 'wines',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },

  // WATER & SODA
  {
    id: 'water-1',
    name: 'Soda 300ml',
    description: 'Glass bottle soda',
    price: 150,
    category: 'water',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'water-2',
    name: 'Plastic Soda 500ml',
    description: 'Plastic bottle soda',
    price: 150,
    category: 'water',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'water-3',
    name: 'Sparkling Water 500ml',
    description: 'Sparkling water bottle',
    price: 190,
    category: 'water',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'water-4',
    name: 'Sparkling Water 750ml',
    description: 'Large sparkling water bottle',
    price: 300,
    category: 'water',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'water-5',
    name: 'Urban Mist 500ml',
    description: 'Urban mist drink 500ml',
    price: 160,
    category: 'water',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'water-6',
    name: 'Urban Mist 1L',
    description: 'Urban mist drink 1 liter',
    price: 320,
    category: 'water',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },

  // RETAIL
  {
    id: 'retail-1',
    name: 'Urban Loft Honey 0.3kg',
    description: 'Urban Loft brand honey',
    price: 450,
    category: 'retail',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'retail-2',
    name: 'Urban Loft Honey 0.5kg',
    description: 'Urban Loft brand honey',
    price: 750,
    category: 'retail',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'retail-3',
    name: 'Urban Loft Honey 1kg',
    description: 'Urban Loft brand honey',
    price: 1100,
    category: 'retail',
    image: '/images/menu/placeholder-food.svg',
    available: true,
    dietaryTags: ['vegetarian', 'vegan'],
  },
  {
    id: 'retail-4',
    name: 'Urban Mug',
    description: 'Urban Loft branded mug',
    price: 1350,
    category: 'retail',
    image: '/images/menu/placeholder-food.svg',
    available: true,
  },
];